
Science_and_Technology_Facilities_Council = ["ST/", "ATLAS Upgrades", "ATLAS", "PP/", "GRIDPP"]
Eruopean_Research_Council = ["ERC", "FP7"]
Department_of_Energy = ["DE-", "DOE", "DE"]
Ministerio_de_Ciencia_e_Innovación = ["MCIN"]
Swiss_National_Science_Foundation = ["SNSF", "PCEFP2", "P2SKP3", "P400PB", "IZRJZ3"]
National_Science_Foundation = ["NSF", "AST"]
TAGGS = ["90[A-Za-z]{2}"]
National_Institutes_of_Health = ["^[A-Z]\d{2}[A-Z]{2}\d{6}$"]
Nederlandse_Organisatie_voor_Wetenschappelijk_Onderzoek = ["VI.Veni"]
