H2020_EUROPEAN_RESEARCH_COUNCIL = "F4320338438"

# NSF funders and their sub-branches
NATIONAL_SCIENCE_FOUNDATION = "F4320306076"
DIVISION_OF_MATERIALS_RESEARCH = "F4320337367"
DIVISION_OF_CHEMISTRY = "F4320337393"
DIRECTORATE_FOR_MATHEMATICAL_AND_PHYSICAL_SCIENCES = "F4320332172"
DIVISION_OF_MATHEMATICAL_SCIENCES = "F4320337380"
DIVISION_OF_GRADUATE_EDUCATION = "F4320337368"
DIVISION_OF_MOLECULAR_AND_CELLULAR_BIOSCIENCES = "F4320337397"
DIVISION_OF_ADVANCED_CYBERINFRASTRUCTURE = "F4320337563"
OFFICE_OF_ADVANCED_CYBERINFRASTRUCTURE = "F4320337377"
DIRECTORATE_FOR_COMPUTER_AND_INFORMATION_SCIENCE_AND_ENGINEERING = "F4320332169"
DIVISION_OF_COMPUTING_AND_COMMUNICATION_FOUNDATIONS = "F4320337387"
DIVISION_OF_INDUSTRIAL_INNOVATION_AND_PARTNERSHIPS = "F4320337396"
DIRECTORATE_FOR_BIOLOGICAL_SCIENCES = "F4320332167"
DIRECTORATE_FOR_SOCIAL_BEHAVIORAL_AND_ECONOMIC_SCIENCES = "F4320332173"
DIVISION_OF_ELECTRICAL_COMMUNICATIONS_AND_CYBER_SYSTEMS = "F4320337392"
DIVISION_OF_OCEAN_SCIENCES = "F4320337386"
DIVISION_OF_UNDERGRADUATE_EDUCATION = "F4320337408"
DIVISION_OF_BIOLOGICAL_INFRASTRUCTURE = "F4320337398"
DIVISION_OF_SOCIAL_AND_ECONOMIC_SCIENCES = "F4320337366"
DIVISION_OF_CIVIL_MECHANICAL_AND_MANUFACTURING_INNOVATION = "F4320337391"

NSF_FUNDERS = {
    # NATIONAL_SCIENCE_FOUNDATION: "National Science Foundation",
    # DIVISION_OF_MATERIALS_RESEARCH: "Division of Materials Research",
    # DIVISION_OF_CHEMISTRY: "Division of Chemistry",
    # DIRECTORATE_FOR_MATHEMATICAL_AND_PHYSICAL_SCIENCES: "Directorate for Mathematical and Physical Sciences",
    # DIVISION_OF_MATHEMATICAL_SCIENCES: "Division of Mathematical Sciences",
    # DIVISION_OF_GRADUATE_EDUCATION: "Division of Graduate Education",
    # DIVISION_OF_MOLECULAR_AND_CELLULAR_BIOSCIENCES: "Division of Molecular and Cellular Biosciences",
    # DIVISION_OF_ADVANCED_CYBERINFRASTRUCTURE: "Division of Advanced Cyberinfrastructure",
    # OFFICE_OF_ADVANCED_CYBERINFRASTRUCTURE: "Office of Advanced Cyberinfrastructure",
    # DIRECTORATE_FOR_COMPUTER_AND_INFORMATION_SCIENCE_AND_ENGINEERING: "Directorate for Computer and Information Science and Engineering",
    # DIVISION_OF_COMPUTING_AND_COMMUNICATION_FOUNDATIONS: "Division of Computing and Communication Foundations",
    # DIVISION_OF_INDUSTRIAL_INNOVATION_AND_PARTNERSHIPS: "Division of Industrial Innovation and Partnerships",
    # DIRECTORATE_FOR_BIOLOGICAL_SCIENCES: "Directorate for Biological Sciences",
    # DIRECTORATE_FOR_SOCIAL_BEHAVIORAL_AND_ECONOMIC_SCIENCES: "Directorate for Social, Behavioral and Economic Sciences",
    # DIVISION_OF_ELECTRICAL_COMMUNICATIONS_AND_CYBER_SYSTEMS: "Division of Electrical, Communications and Cyber Systems",
    # DIVISION_OF_OCEAN_SCIENCES: "Division of Ocean Sciences",
    # DIVISION_OF_UNDERGRADUATE_EDUCATION: "Division of Undergraduate Education",
    # DIVISION_OF_BIOLOGICAL_INFRASTRUCTURE: "Division of Biological Infrastructure",
    # DIVISION_OF_SOCIAL_AND_ECONOMIC_SCIENCES: "Division of Social and Economic Sciences",
    DIVISION_OF_CIVIL_MECHANICAL_AND_MANUFACTURING_INNOVATION: "Division of Civil, Mechanical and Manufacturing Innovation",
}