funders = [
    "Division of Intramural Research, National Institute of Allergy and Infectious Diseases",
    "Division of Microbiology and Infectious Diseases, National Institute of Allergy and Infectious Diseases",
    "Eunice Kennedy Shriver National Institute of Child Health and Human Development",
    "Foundation for the National Institutes of Health",
    "National Heart, Lung, and Blood Institute",
    "National Institute of Allergy and Infectious Diseases",
    "National Institute of Arthritis and Musculoskeletal and Skin Diseases",
    "National Institute of Biomedical Imaging and Bioengineering",
    "National Institute of Child Health and Human Development",
    "National Institute of Diabetes and Digestive and Kidney Diseases",
    "National Institute of Environmental Health Sciences",
    "National Institute of General Medical Sciences",
    "National Institute of Mental Health",
    "National Institute of Mental Health and Neurosciences",
    "National Institute of Neurological Disorders and Stroke",
    "National Institute of Standards and Technology",
    "National Institute on Aging",
    "National Institute on Alcohol Abuse and Alcoholism",
    "National Institute on Drug Abuse",
    "National Institutes of Health",
    "Office of Extramural Research, National Institutes of Health",
    "National Eye Institute",
    "U.S. National Library of Medicine",
    "National Center for Complementary and Integrative Health",
    "National Institute on Deafness and Other Communication Disorders",
    "National Cancer Institute",
    "Directorate for Biological Sciences",
    "Directorate for Computer and Information Science and Engineering",
    "Directorate for Mathematical and Physical Sciences",
    "Directorate for Social, Behavioral and Economic Sciences",
    "Division of Biological Infrastructure",
    "Division of Chemical, Bioengineering, Environmental, and Transport Systems",
    "Division of Chemistry",
    "Division of Computing and Communication Foundations",
    "Division of Graduate Education",
    "Division of Industrial Innovation and Partnerships",
    "Division of Materials Research",
    "Division of Mathematical Sciences",
    "Division of Molecular and Cellular Biosciences",
    "Division of Ocean Sciences",
    "Division of Social and Economic Sciences",
    "Division of Undergraduate Education",
    "National Science Foundation",
    "Office of Advanced Cyberinfrastructure",
    "Ministerio de Ciencia e Innovación",
    "Ministerio de Economía y Competitividad",
    "National Natural Science Foundation of China",
    "Seventh Framework Programme",
    "Horizon 2020 Framework Programme",
    "Horizon 2020",
    "H2020 Marie Skłodowska-Curie Actions",
    "HORIZON EUROPE European Research Council",
    "European Commission",
    "HORIZON EUROPE Marie Sklodowska-Curie Actions",
    "Narodowe Centrum Nauki",
    "Japan Society for the Promotion of Science",
    "Agence Nationale de la Recherche",
    "Sweedish Research Council",
    "Deutsche Forschungsgemeinschaft",
    "Knut och Alice Wallenbergs Stiftelse",
    "National Aeronautics and Space Administration",
    "Air Force Office of Scientific Research",
    "Army Research Office",
    "U.S. Department of Energy",
    "Fondo Nacional de Desarrollo Científico y Tecnológico",
    "Science and Technology Facilities Council",
    "Engineering and Physical Sciences Research Council",
    "Schweizerischer Nationalfonds zur Förderung der Wissenschaftlichen Forschung",
    "National Institute on Disability, Independent Living, and Rehabilitation Research",
    "Centers for Disease Control and Prevention",
    "Nederlandse Organisatie voor Wetenschappelijk Onderzoek",
    "Bill and Melinda Gates Foundation",
    "Norges Forskningsråd",
    "Australian Research Council",
    "Office of Science"
]