H2020_EUROPEAN_RESEARCH_COUNCIL = "F4320338438"

# NSF funders and their sub-branches
NATIONAL_SCIENCE_FOUNDATION = "F4320306076"
DIVISION_OF_MATERIALS_RESEARCH = "F4320337367"
DIVISION_OF_CHEMISTRY = "F4320337393"
DIRECTORATE_FOR_MATHEMATICAL_AND_PHYSICAL_SCIENCES = "F4320332172"
DIVISION_OF_MATHEMATICAL_SCIENCES = "F4320337380"
DIVISION_OF_GRADUATE_EDUCATION = "F4320337368"
DIVISION_OF_MOLECULAR_AND_CELLULAR_BIOSCIENCES = "F4320337397"
DIVISION_OF_ADVANCED_CYBERINFRASTRUCTURE = "F4320337563"
OFFICE_OF_ADVANCED_CYBERINFRASTRUCTURE = "F4320337377"
DIRECTORATE_FOR_COMPUTER_AND_INFORMATION_SCIENCE_AND_ENGINEERING = "F4320332169"
DIVISION_OF_COMPUTING_AND_COMMUNICATION_FOUNDATIONS = "F4320337387"
DIVISION_OF_INDUSTRIAL_INNOVATION_AND_PARTNERSHIPS = "F4320337396"
DIRECTORATE_FOR_BIOLOGICAL_SCIENCES = "F4320332167"
DIRECTORATE_FOR_SOCIAL_BEHAVIORAL_AND_ECONOMIC_SCIENCES = "F4320332173"
DIVISION_OF_ELECTRICAL_COMMUNICATIONS_AND_CYBER_SYSTEMS = "F4320337392"
DIVISION_OF_OCEAN_SCIENCES = "F4320337386"
DIVISION_OF_UNDERGRADUATE_EDUCATION = "F4320337408"
DIVISION_OF_BIOLOGICAL_INFRASTRUCTURE = "F4320337398"
DIVISION_OF_SOCIAL_AND_ECONOMIC_SCIENCES = "F4320337366"
DIVISION_OF_CIVIL_MECHANICAL_AND_MANUFACTURING_INNOVATION = "F4320337391"

NSF_FUNDERS = {
    NATIONAL_SCIENCE_FOUNDATION: "National Science Foundation",
    DIVISION_OF_MATERIALS_RESEARCH: "Division of Materials Research",
    DIVISION_OF_CHEMISTRY: "Division of Chemistry",
    DIRECTORATE_FOR_MATHEMATICAL_AND_PHYSICAL_SCIENCES: "Directorate for Mathematical and Physical Sciences",
    DIVISION_OF_MATHEMATICAL_SCIENCES: "Division of Mathematical Sciences",
    DIVISION_OF_GRADUATE_EDUCATION: "Division of Graduate Education",
    DIVISION_OF_MOLECULAR_AND_CELLULAR_BIOSCIENCES: "Division of Molecular and Cellular Biosciences",
    DIVISION_OF_ADVANCED_CYBERINFRASTRUCTURE: "Division of Advanced Cyberinfrastructure",
    OFFICE_OF_ADVANCED_CYBERINFRASTRUCTURE: "Office of Advanced Cyberinfrastructure",
    DIRECTORATE_FOR_COMPUTER_AND_INFORMATION_SCIENCE_AND_ENGINEERING: "Directorate for Computer and Information Science and Engineering",
    DIVISION_OF_COMPUTING_AND_COMMUNICATION_FOUNDATIONS: "Division of Computing and Communication Foundations",
    DIVISION_OF_INDUSTRIAL_INNOVATION_AND_PARTNERSHIPS: "Division of Industrial Innovation and Partnerships",
    DIRECTORATE_FOR_BIOLOGICAL_SCIENCES: "Directorate for Biological Sciences",
    DIRECTORATE_FOR_SOCIAL_BEHAVIORAL_AND_ECONOMIC_SCIENCES: "Directorate for Social, Behavioral and Economic Sciences",
    DIVISION_OF_ELECTRICAL_COMMUNICATIONS_AND_CYBER_SYSTEMS: "Division of Electrical, Communications and Cyber Systems",
    DIVISION_OF_OCEAN_SCIENCES: "Division of Ocean Sciences",
    DIVISION_OF_UNDERGRADUATE_EDUCATION: "Division of Undergraduate Education",
    DIVISION_OF_BIOLOGICAL_INFRASTRUCTURE: "Division of Biological Infrastructure",
    DIVISION_OF_SOCIAL_AND_ECONOMIC_SCIENCES: "Division of Social and Economic Sciences",
    DIVISION_OF_CIVIL_MECHANICAL_AND_MANUFACTURING_INNOVATION: "Division of Civil, Mechanical and Manufacturing Innovation",
}

# NIH and their sub-branches

DIVISION_OF_INTRAMURAL_RESEARCH_NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES = "F4320309123"
DIVISION_OF_MICROBIOLOGY_AND_INFECTIOUS_DISEASES_NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES = "F4320338412"
EUNICE_KENNEDY_SHRIVER_NATIONAL_INSTITUTE_OF_CHILD_HEALTH_AND_HUMAN_DEVELOPMENT = "f4320337611"
NATIONAL_HEART_LUNG_AND_BLOOD_INSTITUTE = "f4320337338"
NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES = "f4320337355"
NATIONAL_INSTITUTE_OF_ARTHRITIS_AND_MUSCULOSKELETAL_AND_SKIN_DISEASES = "f4320337362"
NATIONAL_INSTITUTE_OF_BIOMEDICAL_IMAGING_AND_BIOENGINEERING = "f4320337363"
NATIONAL_INSTITUTE_OF_CHILD_HEALTH_AND_HUMAN_DEVELOPMENT = "f4320337364"
NATIONAL_INSTITUTE_OF_DIABETES_AND_DIGESTIVE_AND_KIDNEY_DISEASES = "f4320337357"
NATIONAL_INSTITUTE_OF_ENVIRONMENTAL_HEALTH_SCIENCES = "f4320337361"
NATIONAL_INSTITUTE_OF_GENERAL_MEDICAL_SCIENCES = "f4320337354"
NATIONAL_INSTITUTE_OF_MENTAL_HEALTH = "f4320337346"
NATIONAL_INSTITUTE_OF_NEUROLOGICAL_DISORDERS_AND_STROKE = "f4320337359"
NATIONAL_INSTITUTE_ON_AGING = "f4320337337"
NATIONAL_INSTITUTE_ON_ALCOHOL_ABUSE_AND_ALCOHOLISM = "f4320337330"
NATIONAL_INSTITUTE_ON_DRUG_ABUSE = "f4320337347"
NATIONAL_INSTITUTES_OF_HEALTH = "f4320332161"
OFFICE_OF_EXTRAMURAL_RESEARCH_NATIONAL_INSTITUTES_OF_HEALTH = "f4320337544"
NATIONAL_EYE_INSTITUTE = "f4320337350"
US_NATIONAL_LIBRARY_OF_MEDICINE = "f4320337372"
NATIONAL_CENTER_FOR_COMPLEMENTARY_AND_INTEGRATIVE_HEALTH = "f4320337593"
NATIONAL_INSTITUTE_ON_DEAFNESS_AND_OTHER_COMMUNICATION_DISORDERS = "f4320337352"
NATIONAL_CANCER_INSTITUTE = "f4320337351"
NATIONAL_CENTER_FOR_ADVANCING_TRANSLATIONAL_SCIENCES = "f4320337472"
NATIONAL_INSTITUTE_ON_MINORITY_HEALTH_AND_HEALTH_DISPARITIES = "f4320337534"
NATIONAL_HUMAN_GENOME_RESEARCH_INSTITUTE = "f4320337348"

NIH_FUNDERS = {
    DIVISION_OF_INTRAMURAL_RESEARCH_NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES:
        "Division of Intramural Research, National Institute of Allergy and Infectious Diseases",

    DIVISION_OF_MICROBIOLOGY_AND_INFECTIOUS_DISEASES_NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES:
        "Division of Microbiology and Infectious Diseases, National Institute of Allergy and Infectious Diseases",

    EUNICE_KENNEDY_SHRIVER_NATIONAL_INSTITUTE_OF_CHILD_HEALTH_AND_HUMAN_DEVELOPMENT:
        "Eunice Kennedy Shriver National Institute of Child Health and Human Development",

    NATIONAL_HEART_LUNG_AND_BLOOD_INSTITUTE:
        "National Heart, Lung, and Blood Institute",

    NATIONAL_INSTITUTE_OF_ALLERGY_AND_INFECTIOUS_DISEASES:
        "National Institute of Allergy and Infectious Diseases",

    NATIONAL_INSTITUTE_OF_ARTHRITIS_AND_MUSCULOSKELETAL_AND_SKIN_DISEASES:
        "National Institute of Arthritis and Musculoskeletal and Skin Diseases",

    NATIONAL_INSTITUTE_OF_BIOMEDICAL_IMAGING_AND_BIOENGINEERING:
        "National Institute of Biomedical Imaging and Bioengineering",

    NATIONAL_INSTITUTE_OF_CHILD_HEALTH_AND_HUMAN_DEVELOPMENT:
        "National Institute of Child Health and Human Development",

    NATIONAL_INSTITUTE_OF_DIABETES_AND_DIGESTIVE_AND_KIDNEY_DISEASES:
        "National Institute of Diabetes and Digestive and Kidney Diseases",

    NATIONAL_INSTITUTE_OF_ENVIRONMENTAL_HEALTH_SCIENCES:
        "National Institute of Environmental Health Sciences",

    NATIONAL_INSTITUTE_OF_GENERAL_MEDICAL_SCIENCES:
        "National Institute of General Medical Sciences",

    NATIONAL_INSTITUTE_OF_MENTAL_HEALTH:
        "National Institute of Mental Health",

    NATIONAL_INSTITUTE_OF_NEUROLOGICAL_DISORDERS_AND_STROKE:
        "National Institute of Neurological Disorders and Stroke",

    NATIONAL_INSTITUTE_ON_AGING:
        "National Institute on Aging",

    NATIONAL_INSTITUTE_ON_ALCOHOL_ABUSE_AND_ALCOHOLISM:
        "National Institute on Alcohol Abuse and Alcoholism",

    NATIONAL_INSTITUTE_ON_DRUG_ABUSE:
        "National Institute on Drug Abuse",

    NATIONAL_INSTITUTES_OF_HEALTH:
        "National Institutes of Health",

    OFFICE_OF_EXTRAMURAL_RESEARCH_NATIONAL_INSTITUTES_OF_HEALTH:
        "Office of Extramural Research, National Institutes of Health",

    NATIONAL_EYE_INSTITUTE:
        "National Eye Institute",

    US_NATIONAL_LIBRARY_OF_MEDICINE:
        "U.S. National Library of Medicine",

    NATIONAL_CENTER_FOR_COMPLEMENTARY_AND_INTEGRATIVE_HEALTH:
        "National Center for Complementary and Integrative Health",

    NATIONAL_INSTITUTE_ON_DEAFNESS_AND_OTHER_COMMUNICATION_DISORDERS:
        "National Institute on Deafness and Other Communication Disorders",

    NATIONAL_CANCER_INSTITUTE:
        "National Cancer Institute",

    NATIONAL_CENTER_FOR_ADVANCING_TRANSLATIONAL_SCIENCES:
        "National Center for Advancing Translational Sciences",

    NATIONAL_INSTITUTE_ON_MINORITY_HEALTH_AND_HEALTH_DISPARITIES:
        "National Institute on Minority Health and Health Disparities",

    NATIONAL_HUMAN_GENOME_RESEARCH_INSTITUTE:
        "National Human Genome Research Institute"
}
